```{r}
library(Seurat)
library(SeuratObject)
library(dplyr)
library(scCustomize)
```

```{r}
DC101 <- readRDS("DC101.rds") 
```

```{r}
DefaultAssay(DC101) <- "RNA"
```

SUBSETTING BY EC MARKERS
```{r}
DC101 <- subset(DC101, Pecam1 !=0 & Cdh5 !=0)
```

```{r}
DC101 <- FindVariableFeatures(DC101, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(DC101)
DC101 <- ScaleData(DC101, features = all.genes)

DC101 <- RunPCA(DC101, features = VariableFeatures(object = DC101))
ElbowPlot(DC101)
```

```{r}
DC101 <- FindNeighbors(DC101, dims = 1:20)
DC101 <- FindClusters(DC101, resolution = 0.5)
DC101 <- RunUMAP(DC101, dims = 1:20)

saveRDS(DC101, "DC101_EC.rds")
```

```{r, fig.width= 10}
DimPlot_scCustom(DC101)
```
```{r, fig.width= 10}
DimPlot_scCustom(DC101, label = FALSE)
```

```{r, fig.width=10}
DimPlot_scCustom(DC101, group.by = "Cluster")
```
```{r, fig.width=10}
DimPlot_scCustom(DC101, group.by = "Cluster", label = TRUE, repel = TRUE)
```

CHECKING FOR CONTAMINATION
```{r}
FeaturePlot_scCustom(DC101, features = c("Hbb.bt", "Neurod1", "Cd63"))
```

```{r, fig.width=15, fig.height=9}
FeaturePlot_scCustom(DC101, features = c("Pecam1","Cdh5","Prox1","Lyve1","Pdpn","Ptprc","Flt4","Zeb1","Zeb2","Snai1","Snai2"), reduction = "umap", order = TRUE)
```
```{r}
Plot_Density_Custom(DC101, features = "Mki67")
```

NO. OF CELLS EXPRESSING MARKERS
```{r}
expression <- data.frame(
    (sum(GetAssayData(DC101)["Pecam1",]!= 0)),
    (sum(GetAssayData(DC101)["Cdh5",]!= 0)),
    (sum(GetAssayData(DC101)["Prox1",]!= 0)),
    (sum(GetAssayData(DC101)["Pdpn",]!= 0)),
    (sum(GetAssayData(DC101)["Lyve1",]!= 0)),
    (sum(GetAssayData(DC101)["Ptprc",]!= 0)),
    (sum(GetAssayData(DC101)["Flt4",]!= 0)),
    (sum(GetAssayData(DC101)["Zeb1",]!= 0)),
    (sum(GetAssayData(DC101)["Zeb2",]!= 0)),
    (sum(GetAssayData(DC101)["Snai1",]!= 0)),
    (sum(GetAssayData(DC101)["Snai2",]!= 0)))

	expression
```

EXPRESSION OF MARKERS OF ALL
```{r}
avg_exp <- data.frame(
  AverageExpression(DC101, assay = "RNA", features = "Zeb1", group.by = "Condition"),
  AverageExpression(DC101, assay = "RNA", features = "Zeb2", group.by = "Condition"),
  AverageExpression(DC101, assay = "RNA", features = "Snai1", group.by = "Condition"),
  AverageExpression(DC101, assay = "RNA", features = "Snai2", group.by = "Condition")
)

avg_exp
```
Mesenchymal & Endothelial Markers
```{r}
AverageExpression(DC101, assay = "RNA", features = "Cdh5", group.by = "Condition")
AverageExpression(DC101, assay = "RNA", features = "Pecam1", group.by = "Condition")
AverageExpression(DC101, assay = "RNA", features = "Vim", group.by = "Condition")
AverageExpression(DC101, assay = "RNA", features = "Fn1", group.by = "Condition")
```

```{r}
AverageExpression(DC101, assay = "RNA", features = "Mki67", group.by = "Condition")
Percent_Expressing(DC101, features = "Mki67", group_by = "Condition")
```

```{r}
per_feat <- data.frame(
  Percent_Expressing(DC101, features = "Zeb1", group_by = "Condition"),
  Percent_Expressing(DC101, features = "Zeb2", group_by = "Condition"),
  Percent_Expressing(DC101, features = "Snai1", group_by = "Condition"),
  Percent_Expressing(DC101, features = "Snai2", group_by = "Condition"))

per_feat
```
```{r}
no <- data.frame(
    (sum(DC101@meta.data$Cluster == "activated artery")),
    (sum(DC101@meta.data$Cluster == "arteries")),
    (sum(DC101@meta.data$Cluster == "breach cell")),
    (sum(DC101@meta.data$Cluster == "capillaries type I")),
    (sum(DC101@meta.data$Cluster == "capillaries type II")),
    (sum(DC101@meta.data$Cluster == "immature")),
    (sum(DC101@meta.data$Cluster == "interferon")),
    (sum(DC101@meta.data$Cluster == "large veins")),
    (sum(DC101@meta.data$Cluster == "lymphatics")),
    (sum(DC101@meta.data$Cluster == "neophalanx")),
    (sum(DC101@meta.data$Cluster == "postcapillary veins")),
    (sum(DC101@meta.data$Cluster == "pre-breach cell")),
    (sum(DC101@meta.data$Cluster == "proliferating")),
    (sum(DC101@meta.data$Cluster == "TEC capillaries")),
    (sum(DC101@meta.data$Cluster == "tip cell")),
    (sum(DC101@meta.data$Cluster == "vein")))

	no
```
```{r}
DotPlot_scCustom(DC101, features = c("Zeb1","Zeb2","Snai1","Snai2"), group.by = "Cluster")
```

EXPRESSION BY CLUSTER
```{r}
AverageExpression(DC101, assay = "RNA", features = "Zeb1", group.by = "Cluster")
AverageExpression(DC101, assay = "RNA", features = "Zeb2", group.by = "Cluster")
AverageExpression(DC101, assay = "RNA", features = "Snai1", group.by = "Cluster")
AverageExpression(DC101, assay = "RNA", features = "Snai2", group.by = "Cluster")
AverageExpression(DC101, assay = "RNA", features = "Mki67", group.by = "Cluster")
```
```{r}
Percent_Expressing(DC101, features = "Zeb1", group_by =  "Cluster")
Percent_Expressing(DC101, features = "Zeb2", group_by =  "Cluster")
Percent_Expressing(DC101, features = "Snai1", group_by = "Cluster")
Percent_Expressing(DC101, features = "Snai2", group_by = "Cluster")
Percent_Expressing(DC101, features = "Mki67", group_by = "Cluster")
```
```{r}
DotPlot_scCustom(DC101, features = c("Zeb1","Zeb2","Snai1","Snai2", "Mki67"), group.by = "Cluster")
```
```{r}
Plot_Density_Custom(DC101, features = "Mki67")
```


```{r, fig.width=12}
#DotPlot_scCustom(DC101, features = c("Apln","Cdh5","Erg","Fgfr1","Flt4","Fstl3","Kdr","Lyve1","Nos3","Pdpn","Pecam1","Prox1","Ptgds","Scl","Tie1","Tie2","Vwf","Wnt5a","Acta2","Cnn1","Col12a1","Col1a1","Col1a2","Col2a1","Col3a1","Col6a1","Ctgf","Fap","Fn1","Lamc2","Ly6a","Mmp14","Mmp2","Mmp9","Notch3","Pcolce","Pdgfrb","Ki67"), group.by = "Cluster")
```

