```{r}
library(Seurat)
library(scCustomize)
library(dplyr)
```

```{r}
DC101 <- readRDS("DC101_EC.rds")
PTK <- readRDS("PTK_EC.rds")
```


```{r}
combined.list <- lapply(X= list(DC101,PTK), FUN = function(x) {
  x<- NormalizeData(x)
  x<- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = combined.list)
```

```{r}
anchors <- FindIntegrationAnchors(object.list = combined.list, anchor.features = features)
```
```{r}
combined <- IntegrateData(anchorset = anchors)
```
```{r}
DefaultAssay(combined) <- "integrated"
```

```{r}
combined <- ScaleData(combined, verbose = FALSE)
combined <- RunPCA(combined, verbose = FALSE)
combined <- RunUMAP(combined, reduction = "pca", dims = 1:30)
combined <- FindNeighbors(combined, reduction = "pca", dims = 1:30)
combined <- FindClusters(combined, resolution = 0.5)
```
```{r, fig.width=25, fig.height=10}
p1 <- DotPlot(TEC, features = c("Zeb1", "Zeb2", "Snai1", "Snai2"), group.by = "Cluster")
p2 <- DotPlot(DC101, features = c("Zeb1", "Zeb2", "Snai1", "Snai2"), group.by = "Cluster")
p3 <- DotPlot(PTK, features = c("Zeb1", "Zeb2", "Snai1", "Snai2"), group.by = "Cluster")
p1+p2+p3
```

```{r, fig.width=15}
p1 <- DimPlot_scCustom(combined, reduction = "umap", group.by = "Condition")
p2 <- DimPlot_scCustom(combined, reduction = "umap", label = TRUE, repel = TRUE)
p1 + p2
```
```{r, fig.width=10}
DimPlot_scCustom(combined)
```
```{r, fig.width=15, fig.height=7}
DimPlot_scCustom(combined, split.by = "Condition", group.by = "Cluster")
```
```{r}
DefaultAssay(combined) <- "RNA"
```

```{R}
Idents(combined) <- combined@meta.data$Condition
Idents(combined)
```
Control v Disease DEG
```{r}
DC101Vptk <- FindMarkers(combined, ident.1 = "PTK", ident.2 = "DC101")
DC101Vptk

write.csv(DC101Vptk, "DC101vPTK.csv")
```


```{r}
Idents(combined) <- combined@meta.data$Cluster
Idents(combined)
```
```{r}
combined$celltype.stim <- paste(Idents(combined), combined$Condition, sep = "_")
combined$celltype <- Idents(combined)
Idents(combined) <- "celltype.stim"
Idents(combined)
```
```{r, fig.width= 4, fig.height=6}
DefaultAssay(combined) <- "RNA"
```
```{r, fig.height= 15, fig.width=10}
DotPlot_scCustom(combined, features = c("Zeb1","Zeb2","Snai1","Snai2","Mki67"), group.by = "celltype.stim") + RotatedAxis()
```
```{r}
```

```{r}
aa<- FindMarkers(combined, ident.1 = "activated artery_PTK", ident.2 = "activated artery_DC101")
aa

write.csv(aa, "aaPTKVaaDC101.csv")
```

```{r}
art<- FindMarkers(combined, ident.1 = "arteries_PTK", ident.2 = "arteries_DC101")
art

write.csv(art, "artPTKVartDC101.csv")
```
```{r}
breach <- FindMarkers(combined, ident.1 = "breach cell_PTK", ident.2 = "breach cell_DC101")
breach

write.csv(breach, "brePTKvbreDC101.csv")
```

```{r}
T1 <- FindMarkers(combined, ident.1 = "capillaries type I_PTK", ident.2 = "capillaries type I_DC101")
T1
write.csv(T1, "t1PTKVt1DC101.csv")
```
```{r}
T2 <- FindMarkers(combined, ident.1 = "capillaries type II_PTK", ident.2 = "capillaries type II_DC101")
T2

write.csv(T2, "t2PTKVt2DC101.csv")
```

```{r}
im <- FindMarkers(combined, ident.1 = "immature_PTK", ident.2 = "immature_DC101")
im

write.csv(im, "imPTKVimDC101.csv")
```


```{r}
int <- FindMarkers(combined, ident.1 = "interferon_PTK", ident.2 = "interferon_DC101")
int

write.csv(int, "intPTKVintDC101.csv")
```



```{r}
lv <- FindMarkers(combined, ident.1 = "large veins_PTK", ident.2 = "large veins_DC101")
lv

write.csv(lv, "lvPTKVlvDC101.csv")
```


```{r}
LEC <- FindMarkers (combined, ident.1 = "lymphatics_PTK", ident.2 = "lymphatics_DC101")
LEC

write.csv(LEC, "lecPTKVlecDC101.csv")
```

```{r}
neo <- FindMarkers (combined,, ident.1 = "neophalanx_PTK", ident.2 = "neophalanx_DC101")
neo

write.csv(neo, "neoPTKVneoDC101.csv")
```


```{r}
pcv1 <- FindMarkers (combined, ident.1 = "postcapillary veins_PTK", ident.2 = "postcapillary veins_DC101")
pcv1

write.csv(pcv1, "pcvPTKVpcvDC101.csv")
```

```{r}
prebreach1 <- FindMarkers (combined, ident.1 = "pre-breach cell_PTK", ident.2 = "pre-breach cell_DC101")
prebreach1

write.csv(prebreach1, "prebPTKVprebDC101.csv")
```


```{r}
prolif1 <- FindMarkers (combined, ident.1 = "proliferating_PTK", ident.2 = "proliferating_DC101")
prolif1

write.csv(prolif1, "prolifPTKVprolifDC101.csv")
```

```{r}
TEC_cap1 <- FindMarkers (combined, ident.1 = "TEC capillaries_PTK", ident.2 = "TEC capillaries_DC101")
TEC_cap1

write.csv(TEC_cap1, "TECcapPTKvTECcapDC101.csv")
```

```{r}
tip1 <- FindMarkers (combined, ident.1 = "tip cell_PTK", ident.2 =  "tip cell_DC101")
tip1

write.csv(tip1, "tipPTKVtipDC101.csv")
```

```{r}
vein <- FindMarkers (combined, ident.1 = "vein_PTK", ident.2 = "vein_DC101")
vein

write.csv(vein, "veinPTKVveinDC101.csv")
```







