```{r}
library(Seurat)
library(scCustomize)
library(dplyr)
```

```{r}
TEC <- readRDS("TEC_EC.rds")
NEC <- readRDS("NEC_EC.rds")
```


```{r}
combined.list <- lapply(X= list(TEC,NEC), FUN = function(x) {
  x<- NormalizeData(x)
  x<- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})

features <- SelectIntegrationFeatures(object.list = combined.list)
```

```{r}
anchors <- FindIntegrationAnchors(object.list = combined.list, anchor.features = features)
```
```{r}
combined <- IntegrateData(anchorset = anchors)
```
```{r}
DefaultAssay(combined) <- "integrated"
```

```{r}
combined <- ScaleData(combined, verbose = FALSE)
combined <- RunPCA(combined, verbose = FALSE)
combined <- RunUMAP(combined, reduction = "pca", dims = 1:30)
combined <- FindNeighbors(combined, reduction = "pca", dims = 1:30)
combined <- FindClusters(combined, resolution = 0.5)
```
```{r}
DefaultAssay(NEC) <- "RNA"
DefaultAssay(TEC) <- "RNA"
```

```{r, fig.width=10}
p1 <- DotPlot(NEC_D, features = c("Zeb1","Zeb2","Snai1","Snai2"), group.by = "Cluster")
p2 <- DotPlot(TEC, features = c("Zeb1","Zeb2","Snai1","Snai2"), group.by = "Cluster")
p1 + p2
```
```{r}
DefaultAssay(combined) <- "RNA"
combined@meta.data
DotPlot_scCustom(combined, features = c("Zeb1","Zeb2","Snai1","Snai2"), group.by = "Cluster", split.by = "Condition")
```


```{r, fig.width=10, fig.height=6}
p1 <- DimPlot_scCustom(combined, group.by = "Condition")
p2 <- DimPlot_scCustom(combined, label = TRUE, repel = TRUE)
p1 + p2
```
```{r}
DimPlot_scCustom(combined, group.by = "Condition")
```
```{r}
DimPlot_scCustom(combined)
```
```{r, fig.width=6}
DimPlot_scCustom(combined, split.by = "Condition", group.by = "Cluster")
```
```{r}
DefaultAssay(combined) <- "RNA"
```

```{R}
Idents(combined) <- combined@meta.data$Condition
Idents(combined)
```
Control v Disease DEG
```{r}
cvd <- FindMarkers(combined, ident.1 = "TEC", ident.2 = "NEC")
cvd

write.csv(cvd,"controlvdisease.csv")
```


```{r}
Idents(combined) <- combined@meta.data$Cluster
Idents(combined)
```
```{r}
combined$celltype.stim <- paste(Idents(combined), combined$Condition, sep = "_")
combined$celltype <- Idents(combined)
Idents(combined) <- "celltype.stim"
Idents(combined)
```
```{r, fig.width= 4, fig.height=6}
DefaultAssay(combined) <- "RNA"

DotPlot(combined, features = c("Zeb1","Zeb2","Snai1","Snai2"), group.by = "celltype.stim") + RotatedAxis()
```
```{r}
DotPlot_scCustom(T, features = c("Zeb1","Zeb2","Snai1","Snai2","Mki67"), group.by = "Cluster") + RotatedAxis()
```

```{r}
artery <- FindMarkers(combined, ident.1 = "activated artery_TEC", ident.2 = "arteries_NEC")
artery

write.csv(artery, "activatedartVartery.csv")
```
```{r}
breach1 <- FindMarkers(combined, ident.1 = "breach cell_TEC", ident.2 = "capillaries type I_NEC")
breach1

write.csv(breach1, "breachvT1.csv")
```
```{r}
breach2 <- FindMarkers(combined, ident.1 = "breach cell_TEC", ident.2 = "capillaries type II_NEC")
breach2

write.csv(breach2, "breachvT2.csv")
```
```{r}
T1 <- FindMarkers(combined, ident.1 = "capillaries type I_TEC", ident.2 = "capillaries type I_NEC")
T1
write.csv(T1, "t1dVt1n.csv")
```
```{r}
T2 <- FindMarkers(combined, ident.1 = "capillaries type II_TEC", ident.2 = "capillaries type II_NEC")
T2

write.csv(T2, "t2dVt2n.csv")
```
```{r}
T21 <- FindMarkers(combined, ident.1 = "capillaries type II_NEC", ident.2 = "capillaries type I_NEC")
T21

write.csv(T21, "t2vt1.csv")
```
```{r}
im1 <- FindMarkers(combined, ident.1 = "immature_TEC", ident.2 = "capillaries type I_NEC")
im1

write.csv(im1, "immatureVt1.csv")
```
```{r}
im2 <- FindMarkers(combined, ident.1 = "immature_TEC", ident.2 = "capillaries type II_NEC")
im2

write.csv(im1, "immatureVt2.csv")
```

```{r}
int1 <- FindMarkers(combined, ident.1 = "interferon_TEC", ident.2 = "capillaries type I_NEC")
int1

write.csv(int1, "interVt1.csv")
```

```{r}
int2 <- FindMarkers(combined, ident.1 = "interferon_TEC", ident.2 = "capillaries type II_NEC")
int2

write.csv(int2, "interVt2.csv")
```

```{r}
lv1 <- FindMarkers(combined, ident.1 = "large veins_TEC", ident.2 = "capillaries type I_NEC")
lv1

write.csv(lv1, "lvVt1.csv")
```
```{r}
lv2 <- FindMarkers(combined, ident.1 = "large veins_TEC", ident.2 = "capillaries type II_NEC")
lv2

write.csv(lv2, "lvVt2.csv")
```

```{r}
LEC <- FindMarkers (combined, ident.1 = "lymphatics_TEC", ident.2 = "lymphatics_NEC")
LEC

write.csv(LEC, "lectVlecn.csv")
```

```{r}
neo1 <- FindMarkers (combined,, ident.1 = "neophalanx_TEC", ident.2 = "capillaries type I_NEC")
neo1

write.csv(neo1, "neoVt1.csv")
```
```{r}
neo2 <- FindMarkers (combined,, ident.1 = "neophalanx_TEC", ident.2 = "capillaries type II_NEC")
neo2

write.csv(neo2, "neoVt2.csv")
```

```{r}
pcv1 <- FindMarkers (combined, ident.1 = "postcapillary veins_TEC", ident.2 = "capillaries type I_NEC")
pcv1

write.csv(pcv1, "pcvVt1.csv")
```
```{r}
pcv2 <- FindMarkers (combined, ident.1 = "postcapillary veins_TEC", ident.2 = "capillaries type II_NEC")
pcv2

write.csv(pcv2, "neoVt2.csv")
```
```{r}
prebreach1 <- FindMarkers (combined, ident.1 = "pre-breach cell_TEC", ident.2 = "capillaries type I_NEC")
prebreach1

write.csv(prebreach1, "prebVt1.csv")
```
```{r}
prebreach2 <- FindMarkers (combined, ident.1 = "pre-breach cell_TEC", ident.2 = "capillaries type II_NEC")
prebreach2

write.csv(prebreach2, "prebVt2.csv")
```

```{r}
prolif1 <- FindMarkers (combined, ident.1 = "proliferating_TEC", ident.2 = "capillaries type I_NEC")
prolif1

write.csv(prolif1, "prolifVt1.csv")
```
```{r}
prolif2 <- FindMarkers (combined, ident.1 = "proliferating_TEC", ident.2 = "capillaries type II_NEC")
prolif2

write.csv(prebreach2, "prolifVt2.csv")
```

```{r}
TEC_cap1 <- FindMarkers (combined, ident.1 = "TEC capillaries_TEC", ident.2 = "capillaries type I_NEC")
TEC_cap1

write.csv(TEC_cap1, "TECcVt1.csv")
```
```{r}
TEC_cap2<- FindMarkers (combined, ident.1 = "TEC capillaries_TEC", ident.2 = "capillaries type II_NEC")
TEC_cap2

write.csv(TEC_cap2, "TECcVt2.csv")
```

```{r}
tip1 <- FindMarkers (combined, ident.1 = "tip cell_TEC", ident.2 =  "capillaries type I_NEC")
tip1

write.csv(tip1, "tipVt1.csv")
```
```{r}
tip2 <- FindMarkers (combined, ident.1 = "tip cell_TEC", ident.2 =  "capillaries type II_NEC")
tip2

write.csv(tip2, "tipVt2.csv")
```


```{r}
vein <- FindMarkers (combined, ident.1 = "vein_TEC", ident.2 = "vein_NEC")
vein

write.csv(vein, "vein.csv")
```






