```{r}
library(Seurat)
library(SeuratObject)
library(dplyr)
library(scCustomize)
```

```{r}
lung <- readRDS("processed_mouse_lung_data_RAW.rds")
```

```{r}
lung@meta.data
unique(lung@meta.data$Condition)
```
```{r}
DefaultAssay(lung)
```

```{r}
DimPlot_scCustom(lung)
```
```{r}
DimPlot_scCustom(lung, group.by = "Cluster")
```

```{r, fig.width=20, fig.height=5}
DimPlot(lung, split.by = "Condition")
```

```{r, fig.width 16, fig.height=8}
FeaturePlot_scCustom(lung, features = c("Pecam1","Cdh5","Prox1","Lyve1","Pdpn","Ptprc","Flt4","Zeb1","Zeb2","Snai1","Snai2"), reduction = "umap", order = TRUE)
```

SUBSET NEC
```{r}
NEC <- subset(lung, subset = Condition == "NEC")
```

```{r}
NEC <- FindVariableFeatures(NEC, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(NEC)
NEC <- ScaleData(NEC, features = all.genes)

NEC <- RunPCA(NEC, features = VariableFeatures(object = NEC))
ElbowPlot(NEC)
```

```{r}
NEC <- FindNeighbors(NEC, dims = 1:20)
NEC <- FindClusters(NEC, resolution = 0.5)
```

```{r}
NEC <- RunUMAP(NEC, dims = 1:20)
```
```{r}
saveRDS(NEC, "NEC.rds")
```

SUBSET TEC
```{r}
TEC <- subset(lung, subset = Condition == "TEC")
```	
```{r}	
TEC <- FindVariableFeatures(TEC, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(TEC)
TEC <- ScaleData(TEC, features = all.genes)
TEC <- RunPCA(TEC, features = VariableFeatures(object = TEC))
ElbowPlot(TEC)
```
```{r}
TEC <- FindNeighbors(TEC, dims = 1:20)
TEC <- FindClusters(TEC, resolution = 0.5)
TEC <- RunUMAP(TEC, dims = 1:20)
```
```{r}
saveRDS(TEC, "TEC.rds")
```

SUBSETTING API242
```{r}
API242 <- subset(lung, subset = Condition == "API242_subcutanous.exp1")
```	
```{r}	
API242 <- FindVariableFeatures(API242, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(API242)
API242 <- ScaleData(API242, features = all.genes)
API242 <- RunPCA(API242, features = VariableFeatures(object = API242))
ElbowPlot(API242)
```
```{r}
API242 <- FindNeighbors(API242, dims = 1:20)
API242 <- FindClusters(API242, resolution = 0.5)
API242 <- RunUMAP(API242, dims = 1:20)
```
```{r}
saveRDS(API242, "API242.rds")
```

SUBSET PTK
```{r}
PTK <- subset(lung, subset = Condition == "PTK")
```	
```{r}	
PTK <- FindVariableFeatures(PTK, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(PTK)
PTK <- ScaleData(PTK, features = all.genes)
PTK <- RunPCA(PTK, features = VariableFeatures(object = PTK))
ElbowPlot(PTK)
```
```{r}
PTK <- FindNeighbors(PTK, dims = 1:20)
PTK <- FindClusters(PTK, resolution = 0.5)
PTK <- RunUMAP(PTK, dims = 1:20)
```
```{r}
saveRDS(PTK, "PTK.rds")
```

SUBSETTING DC101
```{r}
DC101 <- subset(lung, subset = Condition == "DC101")
```	
```{r}	
DC101 <- FindVariableFeatures(DC101, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(DC101)
DC101 <- ScaleData(DC101, features = all.genes)
DC101 <- RunPCA(DC101, features = VariableFeatures(object = DC101))
ElbowPlot(DC101)
```
```{r}
DC101 <- FindNeighbors(DC101, dims = 1:20)
DC101 <- FindClusters(DC101, resolution = 0.5)
DC101 <- RunUMAP(DC101, dims = 1:20)
```
```{r}
saveRDS(DC101, "DC101.rds")
```
